//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Res
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRoom
    {
        public int id { get; set; }
        public int roomId { get; set; }
        public int clientId { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
        public Nullable<System.DateTime> dateOut { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Room Room { get; set; }
    }
}
