//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int id { get; set; }
        public int floorNumber { get; set; }
        public int roomNumber { get; set; }
        public int categoryId { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
    }
}
