//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usr
    {
        public int id { get; set; }
        public string login { get; set; }
        public string passwd { get; set; }
        public int roleId { get; set; }
        public System.DateTime lastLogDate { get; set; }
        public string name { get; set; }
        public Nullable<int> blockStatusId { get; set; }
        public bool FirstLogin { get; set; }
    
        public virtual AccStatu AccStatu { get; set; }
        public virtual Role Role { get; set; }
    }
}
